spring:
  config:
    activate:
      on-profile: dev, prod
  application:
    name: telegram-recruiter
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_recruiter
    username: postgres
    password: zaq1@WSX
    driver-class-name: org.postgresql.Driver
  security:
    request-matchers:
      permit-all: >
        POST /login/telegram,
        PATCH /candidates/**/notifications/**
    jwt:
      secret: fjnkhjvbnmkldnskfifjeodklmscvfnjldiosklmcdnfjo
      expiration-time-millis: 604800000
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: prod
server:
  ssl:
    key-store: classpath:keystore/recruiter-keystore.p12
    key-store-password:
