spring:
  application:
    name: telegram-recruiter
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_recruiter
    username: postgres
    password: zaq1@WSX
    driver-class-name: org.postgresql.Driver
  security:
    request-matchers:
      permit-all: >
        POST /login/telegram
    jwt:
      secret: fjnkhjvbnmkldnskfifjeodklmscvfnjldiosklmcdnfjo
      expiration-time-millis: 604800000
server:
  port: 8081
